---
- name: Create certs
  hosts: all
  become: true
  tasks:
    - name: Install packages
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - gnutls-bin
        - ssl-cert
      when: inventory_hostname in groups["master"]

    - name: Create key for certificate authority
      command: certtool --generate-privkey --bits 4096 --outfile /etc/ssl/private/mycakey.pem
      when: inventory_hostname in groups["master"]

    - name: Create ca.info
      copy:
        dest: "/etc/ssl/ca.info"
        content: |
          cn = Laboratorio de Sistemas Distibuidos
          ca
          cert_signing_key
          expiration_days = 3650
      when: inventory_hostname in groups["master"]

    - name: Create self-signed certificate
      command: certtool --generate-self-signed --load-privkey /etc/ssl/private/mycakey.pem --template /etc/ssl/ca.info --outfile /usr/local/share/ca-certificates/mycacert.crt
      when: inventory_hostname in groups["master"]

    - name: Update CA certificates
      command: update-ca-certificates
      when: inventory_hostname in groups["master"]

    - name: Create key for servers1
      command: certtool --generate-privkey --bits 2048 --outfile /tmp/ldap-1_key.pem #/etc/ldap/
      when: inventory_hostname in groups["master"]

    - name: Create key for servers2
      command: certtool --generate-privkey --bits 2048 --outfile /tmp/ldap-2_key.pem #/etc/ldap/
      when: inventory_hostname in groups["master"]
   
    - name: Create key for servers3
      command: certtool --generate-privkey --bits 2048 --outfile /tmp/ldap-3_key.pem #/etc/ldap/
      when: inventory_hostname in groups["master"]

    - name: Changing mode keys
      file:
        path: /tmp/ldap-1_key.pem
        owner: root
        group: root
        mode: 0644
      when: inventory_hostname in groups["master"]

    - name: Changing mode keys
      file:
        path: /tmp/ldap-2_key.pem
        owner: root
        group: root
        mode: 0644
      when: inventory_hostname in groups["master"]

    - name: Changing mode keys
      file:
        path: /tmp/ldap-3_key.pem
        owner: root
        group: root
        mode: 0644
      when: inventory_hostname in groups["master"]

    - name: Copy private key to servers
      copy:
        src: /tmp/{{ inventory_hostname}}_key.pem
        dest: /etc/ldap/{{ inventory_hostname }}_key.pem
        owner: root
        group: root
        mode: 0640

    - name: Create ldap-1 cert info 
      copy:
        dest: "/tmp/ldap-1.info" #/etc/ssl/
        content: |
          organization = Organization example
          cn = ldap-1.example.com
          tls_www_server
          encryption_key
          signing_key
          expiration_days = 365
      when: inventory_hostname in groups["master"]

    - name: Create ldap-2 cert info 
      copy:
        dest: "/tmp/ldap-2.info" #/etc/ssl/
        content: |
          organization = Organization example
          cn = ldap-2.example.com
          tls_www_server
          encryption_key
          signing_key
          expiration_days = 365
      when: inventory_hostname in groups["master"]

    - name: Create ldap-3 cert info 
      copy:
        dest: "/tmp/ldap-3.info" #/etc/ssl/
        content: |
          organization = Organization example
          cn = ldap-3.example.com
          tls_www_server
          encryption_key
          signing_key
          expiration_days = 365
      when: inventory_hostname in groups["master"]

    - name: Create ldap-1 certificate
      command: certtool --generate-certificate --load-privkey /tmp/ldap-1_key.pem --load-ca-certificate /etc/ssl/certs/mycacert.pem --load-ca-privkey /etc/ssl/private/mycakey.pem --template /tmp/ldap-1.info --outfile /tmp/ldap-1_cert.pem
      when: inventory_hostname in groups["master"]

    - name: Create ldap-2 certificate
      command: certtool --generate-certificate --load-privkey /tmp/ldap-2_key.pem --load-ca-certificate /etc/ssl/certs/mycacert.pem --load-ca-privkey /etc/ssl/private/mycakey.pem --template /tmp/ldap-2.info --outfile /tmp/ldap-2_cert.pem
      when: inventory_hostname in groups["master"]

    - name: Create ldap-3 certificate
      command: certtool --generate-certificate --load-privkey /tmp/ldap-3_key.pem --load-ca-certificate /etc/ssl/certs/mycacert.pem --load-ca-privkey /etc/ssl/private/mycakey.pem --template /tmp/ldap-3.info --outfile /tmp/ldap-3_cert.pem
      when: inventory_hostname in groups["master"]

    - name: Copy private certificate to servers
      copy:
        src: /tmp/{{ inventory_hostname}}_cert.pem
        dest: /etc/ldap/{{ inventory_hostname }}_cert.pem
        owner: root
        group: root
        mode: 0644

    - name: Copy my CA cert
      copy:
        src: /usr/local/share/ca-certificates/mycacert.crt
        dest: /usr/local/share/ca-certificates/mycacert.crt
        owner: root
        group: root

    - name: Update certificates
      command: update-ca-certificates
      when: inventory_hostname in groups["consumers"]
